"""Data-quality profiling for application_train.csv.

Generates a human-readable Markdown report at ``reports/data_quality_report.md``
covering row/column counts, dtype breakdown, and a missingness ranking.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

DEFAULT_REPORT_PATH = Path("reports") / "data_quality_report.md"

# Threshold above which a column is flagged as "too sparse to keep" in Phase 1 cleaning.
DROP_MISSING_THRESHOLD: float = 0.60


def _dtype_counts(df: pd.DataFrame) -> dict[str, int]:
    """Count columns per dtype family (int / float / object / bool / other)."""
    families: dict[str, int] = {
        "int": 0,
        "float": 0,
        "object": 0,
        "bool": 0,
        "other": 0,
    }
    for dtype in df.dtypes:
        name = str(dtype)
        if name.startswith("int"):
            families["int"] += 1
        elif name.startswith("float"):
            families["float"] += 1
        elif name == "bool":
            families["bool"] += 1
        elif name == "object":
            families["object"] += 1
        else:
            families["other"] += 1
    return families


def profile_dataframe(
    df: pd.DataFrame,
    *,
    drop_threshold: float = DROP_MISSING_THRESHOLD,
) -> dict:
    """Build a profiling summary for the given dataframe.

    Parameters
    ----------
    df : pd.DataFrame
        The dataframe to profile.
    drop_threshold : float
        Missing-fraction above which a column would be dropped by cleaning.

    Returns
    -------
    dict
        Keys: ``n_rows``, ``n_cols``, ``dtypes`` (dict of family -> count),
        ``missing_pct`` (Series sorted descending), ``high_missing`` (list of
        column names whose missing fraction exceeds ``drop_threshold``).
    """
    missing_pct = df.isna().mean().sort_values(ascending=False)
    high_missing = missing_pct[missing_pct > drop_threshold].index.tolist()

    return {
        "n_rows": int(df.shape[0]),
        "n_cols": int(df.shape[1]),
        "dtypes": _dtype_counts(df),
        "missing_pct": missing_pct,
        "high_missing": high_missing,
        "drop_threshold": drop_threshold,
    }


def _render_markdown(profile: dict) -> str:
    """Render the profile dict as a Markdown report."""
    lines: list[str] = []
    lines.append("# Data Quality Report — application_train.csv")
    lines.append("")
    lines.append("Generated by `src.data.profile` (Phase 1).")
    lines.append("")

    # 1. Shape
    lines.append("## 1. Shape")
    lines.append("")
    lines.append(f"- Rows: **{profile['n_rows']:,}**")
    lines.append(f"- Columns: **{profile['n_cols']}**")
    lines.append("")

    # 2. Dtype breakdown
    lines.append("## 2. Dtype Breakdown")
    lines.append("")
    lines.append("| Dtype family | Column count |")
    lines.append("|---|---|")
    for family, count in profile["dtypes"].items():
        lines.append(f"| {family} | {count} |")
    lines.append("")

    # 3. Missingness top 20
    lines.append("## 3. Top 20 Columns by Missing Fraction")
    lines.append("")
    lines.append("| Rank | Column | Missing % |")
    lines.append("|---|---|---|")
    for i, (col, frac) in enumerate(profile["missing_pct"].head(20).items(), start=1):
        lines.append(f"| {i} | `{col}` | {frac:.2%} |")
    lines.append("")

    # 4. Columns flagged for drop
    lines.append(
        f"## 4. Columns with >{profile['drop_threshold']:.0%} Missing (Flagged for Drop)"
    )
    lines.append("")
    if profile["high_missing"]:
        lines.append(f"**{len(profile['high_missing'])} column(s)** exceed the threshold:")
        lines.append("")
        for col in profile["high_missing"]:
            frac = profile["missing_pct"][col]
            lines.append(f"- `{col}` — {frac:.2%} missing")
    else:
        lines.append("_No columns exceed the threshold._")
    lines.append("")

    # 5. Target distribution (only if TARGET present)
    lines.append("## 5. Target Distribution (if present)")
    lines.append("")
    lines.append("(Filled in by `profile_dataframe` caller — see cleaning_summary.md for the post-clean target balance.)")
    lines.append("")

    return "\n".join(lines)


def write_report(
    df: pd.DataFrame,
    *,
    report_path: str | Path = DEFAULT_REPORT_PATH,
    drop_threshold: float = DROP_MISSING_THRESHOLD,
) -> Path:
    """Profile ``df`` and write the Markdown report to ``report_path``.

    Returns the resolved output path.
    """
    profile = profile_dataframe(df, drop_threshold=drop_threshold)
    md = _render_markdown(profile)

    out = Path(report_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    return out


if __name__ == "__main__":
    # CLI entry: load, profile, write report.
    from src.data.load import load_application_train

    df = load_application_train()
    out_path = write_report(df)
    print(f"Wrote data quality report to {out_path}")
    print(
        f"Shape: {df.shape}; "
        f"dtype breakdown: {profile_dataframe(df)['dtypes']}; "
        f"columns >60% missing: {len(profile_dataframe(df)['high_missing'])}"
    )
